### ISSUE TITLE
not activate this verction

### ISSUE THREAD

**Issue by CHSUDHAKAR86** [GravityPDF/gravity-pdf-core-booster#33]
please solve this issue booster loder error in php code 64 line

**Comment by jakejackson1** [comment]
Closing for now as you've not provided enough information about the problem you're having. Please feel free to add additional details such as the actual error message you're seeing, what steps you took after cloning this repo, and any other relevant details and we I can look into it further.

**Comment by CHSUDHAKAR86** [comment]
dear jakejackson sir
This issue i will explain 
i send two images 1 is 
![IMAGE 1](https://user-images.githubusercontent.com/49674560/56314501-e48b2100-6172-11e9-9fb9-86dbc32cc0ac.jpg)

second one is 
![image 2](https://user-images.githubusercontent.com/49674560/56314565-097f9400-6173-11e9-975c-9d207b4ed685.jpg)

above first image show 
gravity forms plugin and pdf is active but core booster not activate 

second image 
gravity forms plugin and core booster is active but gravity pdf not activate  

in case gravity pdf plugin and core booster is active but  gravity forms not activate 

why did to happen to this issue

**Comment by jakejackson1** [comment]
What's the exact error message generated when the internal server error occurs? This will be in your server error logs.

**Comment by CHSUDHAKAR86** [comment]
HOW TO ACTIVATE ALL PLUGINS STEP BY STEP PLEASE

**Comment by jakejackson1** [comment]
@CHSUDHAKAR86 sorry, Github isn't the place for user support about the plugin, but a place for developers to report bugs (with specific errors messages) or suggest feedback. If you'd like user support for Gravity PDF Core Booster, [you'll first need to purchased a license](https://gravitypdf.com/shop/core-booster-add-on/) and [you can then use our Support ticket system](https://gravitypdf.com/support/).
